javac Network/Builder/RequestBuilder.java
javac Network/Builder/POSTRequestBuilder.java
javac Network/Builder/GETRequestBuilder.java
javac Network/Client/Client.java
javac Network/Client/Response.java
javac Network/Server/Server.java
javac Network/Server/ServerWorker.java
javac httpc.java
javac httpf.java
#java  Network/Client.Client 
